### ISSUE TITLE
older version of rxdart

### ISSUE THREAD

**Issue by imranaalam** [chrisedg87/flutter_rounded_loading_button#7] opened 2020-05-11 23:23 UTC

**Comment by imranaalam** [comment] 2020-05-11 23:24
sorry, it's compatible with latest version of rxdart.

**Comment by chrisedg87** [comment] 2020-05-12 18:10
The package currently uses rxdart 0.24.0 which is latest version. Have I misunderstood?

**Comment by chrisedg87** [comment] 2020-06-06 18:36
Closing this as cannot reproduce.

**Closed by chrisedg87** 2020-06-06 18:36 UTC
